config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks, only: [:show, :create]
  root 'home#index'
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :bus
  enum opinion: {good: 'good', bad: 'bad'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  def index
    @buses = Bus.all
  end

  def show
  end

  def new
    @bus = Bus.new
  end

  def edit
  end

  def create
    @bus = Bus.new(bus_params)

    if @bus.save
      render :show, status: :created, location: @bus
    else
      render json: @bus.errors, status: :unprocessable_entity
    end
  end

  def update
    if @bus.update(bus_params)
      render :show, status: :ok, location: @bus
    else
      render json: @bus.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @bus.destroy
    head :no_content
  end

  private
    def set_bus
      @bus = Bus.find(params[:id])
    end

    def bus_params
      params.require(:bus).permit(:identification_number, :line, :company_id)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      render :show, status: :created, location: @company
    else
      render json: @company.errors, status: :unprocessable_entity
    end
  end

  def update
    if @company.update(company_params)
      render :show, status: :ok, location: @company
    else
      render json: @company.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @company.destroy
    head :no_content
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  def index
    @feedbacks = Feedback.all
  end

  def show
    @bus = @feedback.bus
  end

  def create
    @feedback = Feedback.new(feedback_params.except(:bus))
    @bus = get_or_create_bus
    @feedback.bus = @bus

    if @feedback.save
      render :show, status: :created, location: @feedback
    else
      render json: @feedback.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @feedback.destroy
    head :no_content
  end

  private
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    def get_or_create_bus
      bus_params = feedback_params[:bus]
      Bus.where(bus_params).first_or_create do |bus|
        bus.identification_number = bus_params[:identification_number]
        bus.line = bus_params[:line]
      end
    end

    def feedback_params
      params.require(:feedback).permit(:content, :latitude, :longitude, :opinion, :user, :sent_at, bus: [:line, :identification_number])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_maps(latitude, longitude, mobile=false)
    key_mobile = "AIzaSyDWQW6g_ZXa_pANLFoAHFaK8oC6KOGKU4U"
    key_web = "AIzaSyCC9UY8MCMY3PBx25McZ9QezjQb576djEI"
    key = nil

    if mobile
      key = key_mobile
    else
      key = key_web
    end

    url_maps = (
        "http://maps.googleapis.com/maps/api/staticmap?" +
        "center=#{latitude},#{longitude}" +
        "&zoom=16&scale=false&size=700x280&maptype=roadmap&sensor=false&format=png&visual_refresh=true&" +
        "markers=#{latitude},#{longitude}" +
        "&key=#{key}"
    )

    url_maps
  end

  def canonical_url
    url_for(only_path: false, overwrite_params: nil)
  end
end

app/views/buses/_form.html.erb
<%= form_for(@bus) do |f| %>
  <% if @bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% @bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identification_number %><br>
    <%= f.text_field :identification_number %>
  </div>
  <div class="field">
    <%= f.label :line %><br>
    <%= f.text_field :line %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing Bus</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buses</h1>

<table>
  <thead>
    <tr>
      <th>Identification number</th>
      <th>Line</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= bus.identification_number %></td>
        <td><%= bus.line %></td>
        <td><%= bus.company %></td>
        <td><%= link_to 'Show', bus %></td>
        <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
        <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New Bus</h1>

<%= render 'form' %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identification number:</strong>
  <%= @bus.identification_number %>
</p>

<p>
  <strong>Line:</strong>
  <%= @bus.line %>
</p>

<p>
  <strong>Company:</strong>
  <%= @bus.company %>
</p>

<%= link_to 'Edit', edit_bus_path(@bus) %> |
<%= link_to 'Back', buses_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Opinion</th>
      <th>User</th>
      <th>Sent at</th>
      <th>Bus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.content %></td>
        <td><%= feedback.latitude %></td>
        <td><%= feedback.longitude %></td>
        <td><%= feedback.opinion %></td>
        <td><%= feedback.user %></td>
        <td><%= feedback.sent_at %></td>
        <td><%= feedback.bus %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/show.html.erb
<% content_for :specific_meta_tags do %>
  <title>Avaliação › Busão Nota 10</title>
  <meta name="description" content="<%= @feedback.content %>">
  <meta property="og:description" content="<%= @feedback.content %>" />
<% end %>

<header class="intro-app small">
  <div class="container">
    <div class="brand">
      <%= link_to(root_path, class: 'logo-name') do %>
        <%= image_tag("logo@2x.png", class: 'logo') %>
        <div class="name">
          <h1>Busão Nota 10</h1>
          <h2>Melhore o transporte do Rio</h2>
        </div>
      <% end %>
      <a class="right" href="#">
        <button><span class="android"></span>Baixe Grátis</button>
      </a>
    </div>
  </div>
</header>

<section class="feedbacks container">
  <div class="date">
    <div class="col-1-6 top left">
      <h1>
        <%= I18n.localize(@feedback.sent_at, format: "%d") %>
      </h1>
      <h6><%= I18n.localize(@feedback.sent_at, format: "%b %Y").downcase %></h6>
    </div>
    <ul class="col-4-6">
      <li class="feedback">
        <%= image_tag(image_maps(@feedback.latitude, @feedback.longitude)) %>
        <div class="message">
          <figure class="status left">
            <% if @feedback.good? %>
              <%= image_tag("icon-smile-happy.svg") %>
            <% else %>
              <%= image_tag("icon-smile-sad.svg") %>
            <% end %>
          </figure>
          <div class="text">
            <div class="bus-data">
              <div class="grid-1-2 left">
                <label>Veículo</label>
                <p><%= @feedback.bus.identification_number %></p>
              </div>
              <div class="grid-1-2">
                <label>Linha</label>
                <p><%= @feedback.bus.line %></p>
              </div>
            </div>
            <div class="comment">
              <label>Comentário</label>
              <p><%= @feedback.content %></p>
            </div>
            <p><%= time_ago_in_words(@feedback.sent_at) %></p>
          </div>
        </div>
      </li>
    </ul>
  </div>
</section>

<footer>
  <div class="container">
    <div class="vote-rioapps grid-1-2">
      <h4>Curtiu o Applicativo?</h4>
      <h5>Vote na gente no concurso Rio Apps!</h5>
      <a href="#"><button class="blue"><span class="vote"><span>Votar no Rio Apps!</button></a>
    </div>
    <div class="rioapps-logos grid-1-2 right">
      <figure class="grid-1-3 rio450">
        <%= image_tag("logo-rio450anos.jpg") %>
      </figure>
      <figure class="grid-1-3 prefeitura">
        <%= image_tag("logo-prefeitura.png") %>
      </figure>
      <figure class="grid-1-3 rioapps-logo">
        <%= image_tag("logo-rioapps.png") %>
      </figure>
    </div>
  </div>
</footer>

app/views/home/index.html.erb
<% content_for :specific_meta_tags do %>
  <title>Busão Nota 10</title>
  <meta name="description" content="Como você avalia suas viagens de ônibus no Rio? Que tal avaliar suas experiências e compartilhar no facebook para ajudar a melhorar esse serviço?">
  <meta property="og:description" content="Como você avalia suas viagens de ônibus no Rio? Que tal avaliar suas experiências e compartilhar no facebook para ajudar a melhorar esse serviço?" />
<% end %>

<a class="etiqueta" target="_blank" href="http://rioapps.com.br/apps/16">
  <%= image_tag('etiqueta.png') %>
</a>
<section class="intro-app">
  <div class="container">
    <div class="brand">
      <div class="logo-name">
        <%= image_tag("logo@2x.png", class: 'logo') %>
        <div class="name">
          <h1>Busão Nota 10</h1>
        </div>
      </div>
    </div>
    <div>
      <div class="grid-1-2">
        <h1>Melhore o transporte do Rio!</h1>
        <h2>Como você avalia suas viagens de ônibus?</h2>
        <h3>Que tal avaliar suas experiências e compartilhar no facebook para ajudar a melhorar esse serviço?<br>O histórico de avaliações será transparente para toda a comunidade, a prefeitura do Rio e as empresas de ônibus.</h3>
        <a target="_blank" href="https://play.google.com/store/apps/details?id=br.com.busaonota10.production"><button><span class="android"></span>Baixe Grátis</button></a>
        <p>Disponível no Google Play Store</p>
      </div>
      <figure class="grid-1-2 right">
        <%= image_tag("busao-nota-10-mockup2.png", class: 'mockup') %>
      </figure>
    </div>
  </div>
</section>

  <nav class="menu single-page-nav">
    <ul class="container">
        <li><a href="#how-to" class="current">COMO USAR</a></li>
        <li><a href="#mission" class="">MANIFESTO</a></li>
        <li><a href="#about" class="">SOBRE</a></li>
        <li><a href="#team" class="">EQUIPE</a></li>
        <li class="right"><a class="vote" href="#vote" target="_blank"><button>VOTE NO APP</button></a></li>
    </ul>
</nav>

<section id="how-to" class="how-to">
  <div class="container">
    <div class="grid-1-3 left">
      <span>01</span>
      <h4>Insira os dados do veículo</h4>
      <p>Digitar o número do veículo e a linha em que você estava</p>
      <%= image_tag("mockup-step1.png") %>
    </div>
    <div class="grid-1-3 left">
      <span>02</span>
      <h4>Avalie a sua experiência</h4>
      <p>Marque como boa ou ruim, podendo descrever o ocorrido e envie!</p>
      <%= image_tag("mockup-step2.png") %>
    </div>
    <div class="grid-1-3 last">
      <span>03</span>
      <h4>Compartilhe com a galera</h4>
      <p>Compartilhe nas redes sociais (facebook, twitter, whatsapp, etc)</p>
      <%= image_tag("mockup-step3.png") %>
    </div>
  </div>
</section>
<section id="mission" class="mission">
  <div class="container">
    <div class="title">
      <h2>Manifesto</h2>
      <h3>Crenças e motivações para criação do projeto</h3>
    </div>
    <div class="grid-1-3 left">
      <span></span>
      <h4>Colaboração</h4>
      <p>Acreditamos no poder de cada indivíduo de fazer a diferença através da colaboração com suas experiências pessoais, servindo como agentes transformadores em nossa comunidade!</p>
    </div>
    <div class="grid-1-3 left">
      <span></span>
      <h4>Transparência</h4>
      <p>O histórico de informações produzidas é um bem público e deve estar disponível: para a comunidade, para a Prefeitura do Rio e para as empresas de ônibus que atuam na região.</p>
    </div>
    <div class="grid-1-3 last">
      <span></span>
      <h4>Valorização</h4>
      <p>Parabenizar atitudes e serviços positivas e apontar o que pode ser melhorado é o caminho ideal para a valorização e aperfeiçoamento do transporte.</p>
    </div>
  </div>
</section>

<section id="about" class="about">
  <div class="container">
    <div class="text title left">
      <h2>Sobre</h2>
      <p>O app surgiu a partir do Rio 450, um projeto da Prefeitura do Rio de Janeiro comemorativo dos 450 anos da cidade maravilhosa. O Rio 450 anos criou dois concursos, o “Rio Ideias” e o “Rio Apps”.</p>
      <p>O Rio ideias contou com apoio da comunidade para geração e votação das melhores ideias de aplicativos para a cidade.</p>
      <p>O “Rio Apps” é a instrumentalização dessas ideias em novas tecnologias acessíveis para os cariocas, a fim de incentivar e reconhecer os indivíduos que desenvolvam aplicativos inovadores.</p>
      <p>O Busão nota 10 é um aplicativo popular que está participando do "Rio Apps" e foi originado de uma das das top 10 ideias do “Rio Ideias” e tem função social de melhorar o serviço de ônibus para termos uma mobilidade urbana nota 10.</p>
    </div>
  </div>
  <div class="grid-1-2">
    <%= image_tag("about.jpg") %>
  </div>
</section>

<section id="team" class="team">
  <div class="grid-1-2 left">
    <%= image_tag("marcela.jpg", class: 'grid-1-2 left') %>
    <a target="_blank" href="https://www.linkedin.com/pub/marcela-abbade/1a/34/279">
      <div class="grid-1-2">
        <div class="member">
          <h5>Marcela Abbade</h5>
          <p>User Experiece Designer</p>
          <p class="hidden">saiba mais ›</p>
        </div>
      </div>
    </a>
  </div>
  <div class="grid-1-2">
    <%= image_tag("raphael.jpg", class: 'grid-1-2 left') %>
    <a target="_blank" href="https://br.linkedin.com/pub/raphael-cuba/40/771/74/en">
      <div class="grid-1-2">
        <div class="member">
          <h5>Raphael Cuba</h5>
          <p>Desenvolvedor de Software</p>
          <p class="hidden">saiba mais ›</p>
        </div>
      </div>
    </a>
  </div>
</section>

<section id="vote" class="vote">
  <div class="container">
    <div class="title">
      <h6>CURTIU?</h6>
      <h2>vota na gente!</h2>
      <p>Nosso projeto é um forte concorrente do concurso da prefeitura Rio APPs!
        <br>Vote para irmos adiante. Saiba como:</p>
    </div>
    <div class="grid-1-3 left">
      <span class="numerals">01</span>
      <p>Acesse o site do Rio Apps no botão abaixo</p>
    </div>
    <div class="grid-1-3 left">
      <span class="numerals">02</span>
      <p>Faça seu cadastro ou login via facebook</p>
    </div>
    <div class="grid-1-3 last">
      <span class="numerals">03</span>
      <p>Vote no busão nota 10 e deixe seu comentário!</p>
    </div>
    <a target="_blank" href="http://rioapps.com.br/apps/16"><button><span class="star"></span>QUERO VOTAR NO APP</button></a>
  </div>
</section>
<footer class="small">
  <div class="container">
    <a href="#">SUGESTÕES? ENTRE EM CONTATO</a>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="<%= image_path("favicon.ico") %>" type="image/x-icon">
  <link rel="icon" href="<%= image_path("favicon.ico") %>" type="image/x-icon">

  <!--FONTS-->
  <link href='https://fonts.googleapis.com/css?family=Roboto:700,300,400,100' rel='stylesheet' type='text/css'>

  <link rel="image_src" href="<%= image_url("thumb.png") %>" />
  <!--CSS-->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <!-- GOOGLE ROBOTS!-->
  <%= yield :specific_meta_tags %>
  <meta name="robots" content="index,follow">
  <meta name="robots" content="noarchive">
  <meta name="keywords" CONTENT="aplicativo, 'Rio de Janeiro', Rio, Ônibus, Busão, 'Transporte público', app, serviço, transporte, 'prefeitura do Rio', 'Rio Apps', 'concurso rio apps', 'avaliação', 'linha de ônibus', veículo, fetranspor, 'rio 450 anos' ">
  <!-- FACEBOOK META TAGS!-->
  <meta property="og:title" content="Busão Nota 10" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= canonical_url %>" />
  <meta property="og:image:type" content="image/png" />

  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image" content="<%= image_url("thumb.png") %>" />
  <!-- Schema.org markup Google+ -->
  <meta itemprop="name" content="Busão Nota 10">
  <meta itemprop="description" content="Como você avalia suas viagens de ônibus no Rio? Que tal avaliar suas experiências e compartilhar no facebook para ajudar a melhorar esse serviço?">
  <meta itemprop="image" content="<%= image_url("thumb.png") %>">

</head>
<body>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
</body>
</html>